name = "ITensorCorrelators"
uuid = "6b6dea30-58b3-414c-b7c7-5c6ea5923b3e"
authors = ["Niccol√≤ Baldelli <niccolo.baldelli@icfo.eu>, Matthew Fishman <mfishman@flatironinstitute.org>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
Combinatorics = "1"
ITensorMPS = "0.1, 0.2"
ITensors = "0.3.18, 0.4, 0.5, 0.6, 0.7"
TupleTools = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
